### ISSUE TITLE
metadata method result mixes version with build number

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#25]
We should introduce separate field `build`

Run:
```shell
docker run --rm -t epiphanyplatform/azbi metadata
#AzBI | metadata | should print component metadata
labels:
  version: 0.0.1.3678
  name: Azure Basic Infrastructure
  short: azbi
  kind: infrastructure
  provider: azure
  provides-vms: true
  provides-pubips: true
```

_Originally posted by @mkyc in https://github.com/epiphany-platform/epiphany/issue_comments/705568351_

**Comment by toszo** [comment]
@mkyc wouldn't it be good to have build number as last part of the version X.Y.Z.(buildNumber) ?

**Comment by mkyc** [comment]
@toszo in theory we might use `+` sign to stick to Semantic Versioning specs [section 10](https://semver.org/#spec-item-10). Question is do we want it? 

Things to consider: 
 * best would be if we have consistent naming in all places (GitHub release, DockerHub image and later modules repository for CLI configuration) but we already violate it with general rules for our repositories and release in GitHub is named `v0.0.1` not `0.0.1`. 
 * that would mean that in all the places we would need to use that additional `+1231` part of version number, which seams additional overhead.
 * we do not release "nightly builds" and we have private registry for test builds, so in fact anyone else but CI pipelines does not access those images. That means that there will be just one version `0.0.1` and just one version `0.0.2` and adding build number in version does not introduce any new value. 

Saying that, I do not believe we need to have build number in version string, but there is way in spec to do it. I think it would be ok to have this build number in metadata and in release informations, though. What do you think?

**Comment by toszo** [comment]
Ok, I think we should be compliant with SemVer and use "0.0.1" for GH releases and image tags. 
So this metadata will contain: 
```
#AzBI | metadata | should print component metadata
labels:
  version: 0.0.1
  build: 3193
  name: Azure Basic Infrastructure
  short: azbi
  kind: infrastructure
  provider: azure
  provides-vms: true
  provides-pubips: true
```
