### ISSUE TITLE
Add ability to specify subnet details

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/m-azure-basic-infrastructure#46]
**Is your feature request related to a problem? Please describe.**
There is a need to make each subnet configurable, define its  internal module name that will be used to attach VM group to subnet.

**Describe the solution you'd like**
Apply following structure for `subnets` parameter:

```
subnet:
  public:
    - id: unique  # will be used to attach VM groups
      availability_zone: specific/any  # any for random AZ
      net_bits: 4  # net bits allocated for network address
    - ...
  private:
    ...
```

To calculate subnet CIDR blocks [this](https://registry.terraform.io/modules/hashicorp/subnets/cidr/latest) module can be used. Use vnet block as a base.

**Describe alternatives you've considered**
No.

**Additional context**
Have to be implemented before #13
